import { GoogleGenAI, Chat } from "@google/genai";

let chat: Chat | null = null;

function getChatInstance(): Chat {
    if (!chat) {
        if (!process.env.API_KEY) {
            throw new Error("API_KEY environment variable not set.");
        }
        const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
        chat = ai.chats.create({
            model: 'gemini-2.5-flash',
            config: {
                systemInstruction: 'You are a friendly and knowledgeable art historian specializing in Karnataka\'s mural art traditions. You provide concise and interesting information about styles like Chittara and Mysore paintings. When a user asks you to show, draw, create, or generate an image, you first agree enthusiastically, and then on the next line, and only on that line, you write the exact phrase `[PROMPT]:` followed by a detailed, vibrant, and artistic prompt for an AI image generator based on their request. For example: `[PROMPT]: A vibrant wall mural in the Mysore style depicting a scene from the Ramayana, featuring intricate details, gesso work, and a rich color palette of red, green, and gold, set against a temple wall backdrop.`',
            },
        });
    }
    return chat;
}

export async function generateChatResponse(message: string): Promise<string> {
    try {
        const chatInstance = getChatInstance();
        const response = await chatInstance.sendMessage({ message });
        return response.text;
    } catch (error) {
        console.error("Error calling Gemini Chat API:", error);
        if (error instanceof Error) {
            throw new Error(`Failed to get chat response: ${error.message}`);
        }
        throw new Error("An unexpected error occurred during chat response generation.");
    }
}

export async function generateMuralImage(prompt: string): Promise<string> {
    if (!process.env.API_KEY) {
        throw new Error("API_KEY environment variable not set.");
    }

    try {
        const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
              numberOfImages: 1,
              outputMimeType: 'image/jpeg',
              aspectRatio: '1:1',
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error calling Gemini API:", error);
        if (error instanceof Error) {
            throw new Error(`Failed to generate image: ${error.message}`);
        }
        throw new Error("An unexpected error occurred during image generation.");
    }
}